### ISSUE TITLE
openmdao python example usage 

### ISSUE THREAD

**Issue by mskim0401** [byuflowlab/CCBlade.jl#13]
Hi. I am a Python user who is trying to use CCBlade in OpenMDAO framework. Thanks for openmdao/python code in this repo, I could do simple optimization code. 
However, I have some questions. First, I was trying to use example codes in CCBlade.jl/openmdao/python/examples/ folder, most codes require 'ViternaAirfoil' function of openbemt. I think it seems to include Reynolds number correction. How can I use this example codes except openbemt codes?
Second, if I use 'af_from_files' function in utils.py, should I use interpolated and corrected airfoil data? This function seems to have no any corrections about Re and Mach.

I'm not sure if it will be delivered well due to my poor English.
Have a nice day!

**Comment by andrewning** [comment]
I'll defer to @dingraha who did the python side of things.

**Comment by dingraha** [comment]
Hi,

Yes, the examples in `CCBlade.jl/openmdao/python/examples` use some code from OpenBEMT for the airfoil polars because I was comparing CCBlade.jl to OpenBEMT, another BEMT code. But the Python version of CCBlade (like the Julia version) allows you to use whatever function you'd like for the airfoil polars, which you can define through the `airfoil_interp` option of `LocalInflowAngleComp`. CCBlade.jl actually includes an implementation of the Viterna method in `src/airfoils.jl`. It's in Julia, of course, but you could use it as a guide on how to implement it in Python. Or there's the code in `src/airfoilprep.py` in FLOWLab's AirfoilPrep.jl.

For the `af_from_files` function, yes, you're right, there's no Reynolds number or Mach number correction done by that routine. All it does is interpolate airfoil data for a single Mach and Re with the Akima spline routine from SciPy. If you want Reynolds and Mach number corrections with the Python version of CCBlade, you'd need to write that function yourself. But that wouldn't be that difficult—look at `CCBlade.jl/src/airfoils.jl` for how.

All that being said, I haven't actually used the Python version for quite I while—I like using the the Julia version of CCBlade with OpenMDAO.jl to make it callable from Python OpenMDAO optimizations. It's a lot faster than the Python CCBlade, and you can use the nice automatic differentiation libraries available for Julia. The downside is that you'd have to get Julia installed and talking to Python, which is a bit tricky, but not too bad.

**Comment by mskim0401** [comment]
Thank you for details! It is very helpful.

In fact, I'm trying to combine CCBlade with another tool written by Python using OpenMDAO. It's a little difficult to change main code to Julia for now but, I'll keep your suggestion in mind.
