### ISSUE TITLE
OpenBEMT references

### ISSUE THREAD

**Issue by hsteinhaus** [byuflowlab/CCBlade.jl#9]
The code (especially the tests and the airfoil data) contain a lot of references to a Python package called "openbemt". After an hour of googling, I was unable to find any information about that package. The name suggests, that this package might be open source as well. If so, could you please provide a link or another reference where to obtain it? Maybe this reference could be part of the README.md?

**Comment by andrewning** [comment]
openbemt was a name used internally at nasa for a version of this code written in Python for usage in OpenMDAO.  That has since been folded into this repository to share the same name (CCBlade).  There is a Python/OpenMDAO version in this repo (although I'm not sure of its current state/examples @dingraha).

**Comment by hsteinhaus** [comment]
Thanks for the clarification!
